# Generated by Django 4.2 on 2023-07-10 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('card_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visualized', models.BooleanField()),
                ('visual_option', models.CharField(max_length=255, null=True)),
                ('column_used', models.CharField(max_length=255, null=True)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('table_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.tabledata')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
