# Generated by Django 4.2 on 2023-07-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='cards',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
